### PR TITLE
021 kb 3

### PR DESCRIPTION
**Pull request by shaynelar**
- Installed React Router Dom + associated dependencies
- Created top-level route structure for entire client
- Everything is currently at "App" level, we might want to move stuff around later
- I created index route eg: www.ourpage.com/ to be all warehouses page, does this sound correct? 
- Naming of dynamic warehouses pages then become:
 /warehouses/someAction/:dynamicData 

instead of  

 /someAction/:dynamicData 

which i think makes more sense, thoughts?

### CODE REVIEW

**Comment by manecipoglu** [comment]
I think it totally makes more sense to have "/warehouses/someAction/:dynamicData" instead of the other. I did the other way for my BrainFlix project because I took the project description too literally and got warned because of that.

What do you think of using a <Redirect /> component from react-router-dom for the "/" route and direct them to "/warehouses" ?

**Comment by shaynelar** [comment]
> I think it totally makes more sense to have "/warehouses/someAction/:dynamicData" instead of the other. I did the other way for my BrainFlix project because I took the project description too literally and got warned because of that.
> 
> What do you think of using a `<Redirect />` component from react-router-dom for the "/" route and directing them to "/warehouses" ?

Ok I will keep the route how it is then. Also, I like the redirect Idea, I'm just curious if there would be any seo/performance drawbacks of now having actual data living at our index route. Ill look into that and check back

**Comment by manecipoglu** [comment]
> > I think it totally makes more sense to have "/warehouses/someAction/:dynamicData" instead of the other. I did the other way for my BrainFlix project because I took the project description too literally and got warned because of that.
> > What do you think of using a `<Redirect />` component from react-router-dom for the "/" route and directing them to "/warehouses" ?
> 
> Ok I will keep the route how it is then. Also, I like the redirect Idea, I'm just curious if there would be any seo/performance drawbacks of not having actual data living at our index route. I'll look into that and check back

From SEO perspective, I don't think it matters because we are using plain React (meaning the only thing crawlers will see is a div with an id of "root".  They can't parse our JS). As for performance, I'm curious to know as well. One good thing is that `<Redirect />` does not add to the browser history. It just replaces the URL.

**Comment by shaynelar** [comment]
> > > I think it totally makes more sense to have "/warehouses/someAction/:dynamicData" instead of the other. I did the other way for my BrainFlix project because I took the project description too literally and got warned because of that.
> > > What do you think of using a `<Redirect />` component from react-router-dom for the "/" route and directing them to "/warehouses" ?
> > 
> > 
> > Ok I will keep the route how it is then. Also, I like the redirect Idea, I'm just curious if there would be any seo/performance drawbacks of not having actual data living at our index route. I'll look into that and check back
> 
> From SEO perspective, I don't think it matters because we are using plain React (meaning the only thing crawlers will see is a div with an id of "root". They can't parse our JS). As for performance, I'm curious to know as well. One good thing is that `<Redirect />` does not add to the browser history. It just replaces the URL.

Thats true, I forgot we were building an SPA. I made the change anyway. all traffic to index should go to /warehouses

**Pull request merged**
